-- MySQL Script generated by MySQL Workbench
-- qui 28 mai 2020 14:12:32 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Processos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Processos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Processos` DEFAULT CHARACTER SET utf8 ;
USE `Processos` ;

-- -----------------------------------------------------
-- Table `Processos`.`Processos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Processos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Data_Inicio` DATETIME NULL,
  `Status` ENUM('FINALIZADO', 'EM_ANDAMENTO') NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Processos`.`Documentos_Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Documentos_Template` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Local` VARCHAR(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Processos`.`Etapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Etapas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Processos`.`Documentos_Etapas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Documentos_Etapas` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Etapa_ID` INT NOT NULL,
  `Documentos_Template_ID` INT NOT NULL,
  INDEX `fk_Docuementos_Etapas_Etapa_idx` (`Etapa_ID` ASC),
  PRIMARY KEY (`ID`),
  INDEX `fk_Docuementos_Etapas_Documentos_Template1_idx` (`Documentos_Template_ID` ASC),
  CONSTRAINT `fk_Docuementos_Etapas_Etapa`
    FOREIGN KEY (`Etapa_ID`)
    REFERENCES `Processos`.`Etapas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Docuementos_Etapas_Documentos_Template1`
    FOREIGN KEY (`Documentos_Template_ID`)
    REFERENCES `Processos`.`Documentos_Template` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Processos`.`Documentos_Criados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Documentos_Criados` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  `Local` VARCHAR(100) NULL,
  `Data_Criacao` VARCHAR(45) NULL,
  `Documentos_Etapas_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Documentos_Criados_Documentos_Etapas1_idx` (`Documentos_Etapas_ID` ASC),
  CONSTRAINT `fk_Documentos_Criados_Documentos_Etapas1`
    FOREIGN KEY (`Documentos_Etapas_ID`)
    REFERENCES `Processos`.`Documentos_Etapas` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Processos`.`Processos_Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Processos`.`Processos_Documentos` (
  `Documentos_Criados_ID` INT NOT NULL,
  `Processos_ID` INT NOT NULL,
  INDEX `fk_Processos_Documentos_Documentos_Criados1_idx` (`Documentos_Criados_ID` ASC),
  PRIMARY KEY (`Documentos_Criados_ID`, `Processos_ID`),
  CONSTRAINT `fk_Processos_Documentos_Documentos_Criados1`
    FOREIGN KEY (`Documentos_Criados_ID`)
    REFERENCES `Processos`.`Documentos_Criados` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Processos_Documentos_Processos1`
    FOREIGN KEY (`Processos_ID`)
    REFERENCES `Processos`.`Processos` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
